# Generated by Django 4.2.4 on 2023-10-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_inteny',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
