# Generated by Django 4.2.4 on 2023-10-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_payment_inteny_order_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_intent',
        ),
    ]
